spring:
  r2dbc:
    username: admin
    password: admin
    url: r2dbc:postgresql://172.17.0.1:5432/postgre_db
  data:
    r2dbc:
      repositories:
        enabled: true
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: threaddump,heapdump
info:
  contact:
    email: support@tacocloud.com
    phone: 822-625-6831